class_name Tiles

static var BLUE = Vector2i(0,0)
static var WALL = Vector2i(1,0)
static var BLACK = Vector2i(2,0)
static var CRACKED = Vector2i(3,0)
static var BROKEN = Vector2i(4,0)
static var WHITE = Vector2i(5,0)
static var DICE_1 = Vector2i(0,1)
static var DICE_2 = Vector2i(1,1)
static var DICE_3 = Vector2i(2,1)
static var DICE_4 = Vector2i(3,1)
static var DICE_5 = Vector2i(4,1)
static var DICE_6 = Vector2i(5,1)
static var LOW_WALL = Vector2i(0,2)
